export type Car={id:string;brand:string;model:string;year:number;price:number;type:string;fuel:string;hp:number;torque:number;acc:number;speed:number;range:number;image:string;engine:string;drive:string;length:string;mileage:number;condition:string;transmission:string;tagline:string;features:string[];battery?:number;charge?:number};
export const cars:Car[]=[
{id:'porsche-911-gt3',brand:'Porsche',model:'911 GT3',year:2025,price:222500,type:'Sports',fuel:'Petrol',hp:502,torque:450,acc:3.4,speed:311,range:0,image:'porsche',engine:'4.0L naturally aspirated flat-six',drive:'Rear-wheel drive',length:'4,570 × 1,852 × 1,279 mm',mileage:0,condition:'New',transmission:'PDK automatic',tagline:'Born on the track. Built for every road.',features:['Rear-axle steering','Carbon bucket seats','Sport Chrono','Track-focused aerodynamics']},
{id:'bmw-m4',brand:'BMW',model:'M4 Competition',year:2025,price:88900,type:'Sports',fuel:'Petrol',hp:523,torque:650,acc:3.5,speed:290,range:0,image:'bmw',engine:'3.0L twin-turbo inline-six',drive:'All-wheel drive',length:'4,801 × 1,887 × 1,398 mm',mileage:0,condition:'New',transmission:'Automatic',tagline:'Precision with a rebellious streak.',features:['M xDrive','Adaptive M suspension','M carbon roof','Curved digital cockpit']},
{id:'mercedes-amg-gt',brand:'Mercedes-AMG',model:'GT S',year:2019,price:102500,type:'Sports',fuel:'Petrol',hp:515,torque:670,acc:3.8,speed:310,range:0,image:'amg',engine:'4.0L biturbo V8',drive:'Rear-wheel drive',length:'4,546 × 1,939 × 1,288 mm',mileage:18000,condition:'Pre-owned',transmission:'Automatic',tagline:'A grand tourer. An unmistakable pulse.',features:['AMG Ride Control','Performance exhaust','Burmester sound','Nappa leather']},
{id:'audi-rs7',brand:'Audi',model:'RS7 Sportback',year:2022,price:105000,type:'Executive',fuel:'Petrol',hp:591,torque:800,acc:3.6,speed:305,range:0,image:'audi',engine:'4.0L twin-turbo V8',drive:'All-wheel drive',length:'5,009 × 1,950 × 1,424 mm',mileage:12500,condition:'Pre-owned',transmission:'Automatic',tagline:'Everyday composure. Extraordinary intent.',features:['Quattro','RS air suspension','Matrix LED headlights','Virtual cockpit']},
{id:'range-rover-sport',brand:'Land Rover',model:'Range Rover Sport',year:2022,price:79900,type:'SUV',fuel:'Petrol',hp:395,torque:550,acc:5.9,speed:225,range:0,image:'rover',engine:'3.0L turbo inline-six',drive:'All-wheel drive',length:'4,879 × 2,073 × 1,803 mm',mileage:24000,condition:'Pre-owned',transmission:'Automatic',tagline:'Take the long way. In absolute comfort.',features:['Terrain Response','Panoramic roof','Meridian sound','Air suspension']},
{id:'ferrari-296',brand:'Ferrari',model:'296 GTB',year:2024,price:338255,type:'Sports',fuel:'Hybrid',hp:819,torque:740,acc:2.9,speed:330,range:25,image:'ferrari',engine:'3.0L twin-turbo V6 + electric motor',drive:'Rear-wheel drive',length:'4,565 × 1,958 × 1,187 mm',mileage:0,condition:'New',transmission:'Automatic',tagline:'A new definition of driving emotion.',features:['Plug-in hybrid','Active rear spoiler','eManettino','Carbon ceramic brakes'],battery:7.45},
{id:'lamborghini-huracan',brand:'Lamborghini',model:'Huracán LP610-4',year:2018,price:219000,type:'Sports',fuel:'Petrol',hp:602,torque:560,acc:3.2,speed:325,range:0,image:'lambo',engine:'5.2L naturally aspirated V10',drive:'All-wheel drive',length:'4,459 × 1,924 × 1,165 mm',mileage:16000,condition:'Pre-owned',transmission:'Automatic',tagline:'The sound of something unforgettable.',features:['ANIMA driving modes','Carbon ceramic brakes','Lifting system','Full digital instruments']},
{id:'porsche-taycan',brand:'Porsche',model:'Taycan 4S',year:2020,price:68900,type:'Electric',fuel:'Electric',hp:522,torque:640,acc:4.0,speed:250,range:407,image:'taycan',engine:'Dual electric motors',drive:'All-wheel drive',length:'4,963 × 1,966 × 1,379 mm',mileage:21000,condition:'Pre-owned',transmission:'Automatic',tagline:'Soul, electrified.',features:['800V architecture','Adaptive air suspension','Sport Chrono','Curved driver display'],battery:79.2,charge:23},
{id:'bmw-i7',brand:'BMW',model:'i7 xDrive60',year:2023,price:119300,type:'Electric',fuel:'Electric',hp:536,torque:745,acc:4.7,speed:240,range:625,image:'i7',engine:'Dual electric motors',drive:'All-wheel drive',length:'5,391 × 1,950 × 1,544 mm',mileage:0,condition:'New',transmission:'Automatic',tagline:'Your own world. Effortlessly in motion.',features:['Executive Lounge','Theatre Screen','Panoramic Sky Lounge','Bowers & Wilkins sound'],battery:101.7,charge:34},
{id:'mercedes-eqs',brand:'Mercedes-Benz',model:'EQS 450+',year:2022,price:104400,type:'Electric',fuel:'Electric',hp:329,torque:568,acc:6.2,speed:210,range:770,image:'eqs',engine:'Single electric motor',drive:'Rear-wheel drive',length:'5,216 × 1,926 × 1,512 mm',mileage:0,condition:'New',transmission:'Automatic',tagline:'The art of arriving, reimagined.',features:['MBUX cockpit','Rear-axle steering','Burmester sound','Air suspension'],battery:107.8,charge:31}
];
export const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
export const vehicleImage=(c:Car)=>'/cars/'+c.image+'.jpg';
export const demoNotice='Illustrative inventory. Prices in USD, excluding taxes and fees. Specifications and photography may vary by market and option; verify the exact vehicle before purchase.';
