'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,Check} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {cars,money,vehicleImage} from './data';
export function Pick({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[]}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={typeof v==='string'?v:v.value} value={typeof v==='string'?v:v.value}>{typeof v==='string'?v:v.label}</SelectItem>)}</SelectContent></Select></label>}
export function Counter({value}:{value:number}){const ref=useRef<HTMLSpanElement>(null);useEffect(()=>{const el=ref.current!;let frame=0;const obs=new IntersectionObserver(([e])=>{if(!e.isIntersecting)return;obs.disconnect();if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;const start=performance.now();const tick=(t:number)=>{const p=Math.min((t-start)/1100,1);el.textContent=value%1?(value*(1-Math.pow(1-p,3))).toFixed(1):String(Math.round(value*(1-Math.pow(1-p,3))));if(p<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick)});obs.observe(el);return()=>{obs.disconnect();cancelAnimationFrame(frame)}},[value]);return <span ref={ref}>{value}</span>}
export function Finance({price}:{price:number}){const[p,setP]=useState(price),[down,setDown]=useState(Math.round(price*.2)),[rate,setRate]=useState(6.5),[months,setMonths]=useState(60);const principal=Math.max(0,p-down),r=rate/1200,emi=r?principal*r/(1-Math.pow(1+r,-months)):principal/months;return <section className="finance section" id="finance"><div><p className="eyebrow">MAKE IT YOURS</p><h2>A considered<br/>investment.</h2><p className="muted">Explore a payment plan that fits your life.</p></div><div><div className="form-grid">{[['Vehicle price ($)',p,setP,0,10000000],['Down payment ($)',down,setDown,0,p],['Annual interest (%)',rate,setRate,0,30],['Duration (months)',months,setMonths,1,120]].map(([label,val,set,min,max]:any)=><label className="field" key={label}><span>{label}</span><input type="number" min={min} max={max} step={label.includes('interest')?.1:1} value={val} onChange={e=>{const n=Math.min(max,Math.max(min,Number(e.target.value)));set(n);if(label==='Vehicle price ($)'&&down>n)setDown(n)}}/></label>)}</div><div className="emi"><span>ESTIMATED MONTHLY PAYMENT</span><strong>{money(emi)}<small>/ month</small></strong></div><div className="finance-totals"><span>Total interest <b>{money(emi*months-principal)}</b></span><span>Total loan payments <b>{money(emi*months)}</b></span></div><p className="fine">Illustrative estimate, not a finance offer. Excludes taxes, fees and insurance. Down payment is separate from loan payments.</p></div></section>}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export function Enquiry({kind,initialVehicle,onClose}:{kind:string;initialVehicle?:string;onClose?:()=>void}){const[step,setStep]=useState(kind==='test-drive'?1:3),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');const[form,setForm]=useState({vehicle:initialVehicle||cars[0].id,name:'',email:'',phone:'',date:'',time:'10:00',location:'Private appointment',message:'',variant:'Standard specification',color:'Argento silver',finance:'Cash purchase',tradeIn:'No',consent:false});const edit=(key:string,v:any)=>setForm(f=>({...f,[key]:v}));const selected=cars.find(c=>c.id===form.vehicle)!;
 async function submit(e:any){e.preventDefault();setBusy(true);setError('');try{const res=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,kind})});const data=await res.json() as {id:string;error?:string};if(!res.ok)throw Error(data.error||'Please try again.');setReceipt(data.id);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(receipt)return <div className="success"><div className="success-icon"><Check size={32}/></div><p className="eyebrow">A NEW JOURNEY BEGINS</p><h2>{kind==='test-drive'?'Your drive starts here.':'Request received.'}</h2><p>Your {kind==='test-drive'?'test-drive request':'enquiry'} has been saved.</p><p className="muted">{kind==='test-drive'?`${selected.brand} ${selected.model} · ${form.date} at ${form.time}`:'Thank you for your interest in VELOCE.'}</p><p className="fine">Reference {receipt.slice(0,8).toUpperCase()}<br/>Demonstration showroom: no appointment is confirmed and no email has been sent.</p><a className="button light" href="/cars" onClick={onClose}>Back to the collection <ArrowUpRight size={16}/></a></div>;
 return <div className="enquiry"><p className="eyebrow">YOUR PRIVATE APPOINTMENT</p><h2>{kind==='test-drive'?'Feel the difference.':kind==='quote'?'Make it yours.':'Let’s talk automobiles.'}</h2><p className="muted">{kind==='test-drive'?'Some things can only be understood from the driver’s seat.':'Tell us what you have in mind.'}</p>{kind==='test-drive'&&<div className="steps">{['Your machine','Your moment','Your details'].map((s,i)=><span className={step>=i+1?'active':''} key={s}><b>0{i+1}</b>{s}</span>)}</div>}<form onSubmit={submit}>
 {step===1&&<><div className="booking-cars">{cars.map(c=><button type="button" className={form.vehicle===c.id?'selected':''} key={c.id} onClick={()=>edit('vehicle',c.id)}><img src={vehicleImage(c)} alt={c.model}/><span>{c.brand}<b>{c.model}</b></span>{form.vehicle===c.id&&<Check size={18}/>}</button>)}</div><button className="button light" type="button" onClick={()=>setStep(2)}>Select your moment <ArrowRight size={17}/></button></>}
 {step===2&&<><div className="form-grid"><label className="field"><span>Preferred date</span><input aria-label="Preferred date" type="date" min={today()} required value={form.date} onChange={e=>edit('date',e.target.value)}/></label><Pick label="Preferred time" value={form.time} onChange={v=>edit('time',v)} options={['10:00','11:30','13:00','14:30','16:00','17:30']}/><Pick label="Appointment" value={form.location} onChange={v=>edit('location',v)} options={['Private appointment','Virtual consultation']}/></div><p className="fine">Your preferred time is a request, subject to confirmation.</p><div className="form-actions"><button className="button" type="button" onClick={()=>setStep(1)}>Back</button><button className="button light" type="button" disabled={!form.date||form.date<today()} onClick={()=>setStep(3)}>Your details <ArrowRight size={17}/></button></div></>}
 {step===3&&<>{kind==='test-drive'&&<div className="booking-summary"><img src={vehicleImage(selected)} alt={selected.model}/><div><strong>{selected.brand} {selected.model}</strong><p>{form.date} · {form.time} · {form.location}</p></div></div>}{kind==='quote'&&<div className="form-grid"><Pick label="Vehicle" value={form.vehicle} onChange={v=>edit('vehicle',v)} options={cars.map(c=>({value:c.id,label:c.brand+' '+c.model}))}/><Pick label="Variant" value={form.variant} onChange={v=>edit('variant',v)} options={['Standard specification','Bespoke options consultation']}/><Pick label="Preferred colour" value={form.color} onChange={v=>edit('color',v)} options={['Argento silver','Nero graphite','Rosso red','Pearl white','Discuss bespoke colours']}/><Pick label="Purchase preference" value={form.finance} onChange={v=>edit('finance',v)} options={['Cash purchase','Finance consultation','Lease consultation']}/><Pick label="Trade-in" value={form.tradeIn} onChange={v=>edit('tradeIn',v)} options={['No','Yes']}/></div>}<div className="form-grid">{[['name','Full name','text'],['email','Email address','email'],['phone','Phone number','tel']].map(([key,label,type])=><label className="field" key={key}><span>{label}</span><input required type={type} minLength={key==='name'?2:undefined} maxLength={key==='name'?120:254} value={(form as any)[key]} onChange={e=>edit(key,e.target.value)} autoComplete={key==='name'?'name':key==='phone'?'tel':'email'}/></label>)}</div><label className="field"><span>Anything else we should know?</span><textarea rows={3} maxLength={2000} value={form.message} onChange={e=>edit('message',e.target.value)}/></label><label className="check-label"><Checkbox checked={form.consent} onCheckedChange={v=>edit('consent',v===true)}/><span>I agree to my details being stored for this enquiry. <a href="/privacy">Privacy notice</a></span></label><p className="fine">Demo showroom: requests are saved, but specialist notifications are not connected yet.</p>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions">{kind==='test-drive'&&<button type="button" className="button" onClick={()=>setStep(2)}>Back</button>}<button className="button light" disabled={busy||!form.consent} type="submit">{busy?'Saving…':kind==='test-drive'?'Request your test drive':'Send enquiry'} <ArrowUpRight size={16}/></button></div></>}
 </form></div>}

