'use client';
import {useEffect,useRef,useState} from 'react';
import {RotateCcw,Maximize,Pause,Play} from 'lucide-react';
export default function Studio(){
 const host=useRef<HTMLDivElement>(null),api=useRef<any>(null);const[ready,setReady]=useState(false),[error,setError]=useState(false),[paint,setPaint]=useState('#b9bec4'),[rotate,setRotate]=useState(true);
 useEffect(()=>{let disposed=false,cleanup=()=>{}; const el=host.current!;
 (async()=>{try{
 const THREE=await import('three');const{GLTFLoader}=await import('three/examples/jsm/loaders/GLTFLoader.js');const{DRACOLoader}=await import('three/examples/jsm/loaders/DRACOLoader.js');const{OrbitControls}=await import('three/examples/jsm/controls/OrbitControls.js');const{RoomEnvironment}=await import('three/examples/jsm/environments/RoomEnvironment.js');if(disposed)return;
 const scene=new THREE.Scene();scene.background=new THREE.Color('#111315');scene.fog=new THREE.Fog('#111315',15,40);
 const camera=new THREE.PerspectiveCamera(35,el.clientWidth/el.clientHeight,.1,100);camera.position.set(6,2.6,7).multiplyScalar(Math.max(1,1.35/camera.aspect));
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.8));renderer.setSize(el.clientWidth,el.clientHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;el.appendChild(renderer.domElement);
 const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();const environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;room.dispose();pmrem.dispose();
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.5,0);controls.enableDamping=true;controls.enablePan=false;controls.enableZoom=false;controls.minDistance=5;controls.maxDistance=24;controls.maxPolarAngle=Math.PI/2.1;controls.autoRotate=!matchMedia('(prefers-reduced-motion: reduce)').matches;setRotate(controls.autoRotate);controls.autoRotateSpeed=.6;renderer.domElement.style.touchAction='pan-y';
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#080a0c',roughness:1,metalness:0}));floor.rotation.x=-Math.PI/2;floor.position.y=-.02;scene.add(floor);
 scene.add(new THREE.HemisphereLight(0xffffff,0x444455,1));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(4,8,2);scene.add(light);
 const draco=new DRACOLoader();draco.setDecoderPath('/draco/');const loader=new GLTFLoader();loader.setDRACOLoader(draco);
 const gltf=await loader.loadAsync('/ferrari.glb');if(disposed){renderer.dispose();draco.dispose();return;}const car=gltf.scene;const bounds=new THREE.Box3().setFromObject(car);const size=bounds.getSize(new THREE.Vector3());car.scale.multiplyScalar(4.8/Math.max(size.x,size.y,size.z));bounds.setFromObject(car);const center=bounds.getCenter(new THREE.Vector3());car.position.x-=center.x;car.position.z-=center.z;car.position.y-=bounds.min.y;scene.add(car);const dark=new THREE.MeshStandardMaterial({color:0x171a1e,metalness:.65,roughness:.35});const rubber=new THREE.MeshStandardMaterial({color:0x101114,roughness:.85});car.traverse((o:any)=>{if(!o.isMesh)return;if(/trim|rim|grills|wipers|interior_dark|steering|leather|carpet|carbon/i.test(o.name))o.material=dark;if(o.name==='tire')o.material=rubber;if(o.name==='glass')o.material=new THREE.MeshPhysicalMaterial({color:0x303a42,metalness:.2,roughness:.15,transparent:true,opacity:.4});});const bodyMaterial=new THREE.MeshPhysicalMaterial({color:'#b9bec4',metalness:1,roughness:.2,clearcoat:1,clearcoatRoughness:.1});const body=car.getObjectByName('body') as import('three').Mesh;if(body)body.material=bodyMaterial;
 api.current={paint:(c:string)=>{bodyMaterial.color.set(c)},rotate:(v:boolean)=>{controls.autoRotate=v},zoom:(factor:number)=>{camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target)},reset:()=>{camera.position.set(6,2.6,7).multiplyScalar(Math.max(1,1.35/camera.aspect));controls.target.set(0,.5,0)},key:(v:number)=>{const offset=camera.position.clone().sub(controls.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),v);camera.position.copy(controls.target).add(offset)}};
 let visible=true;const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting});observer.observe(el);const resize=new ResizeObserver(()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();camera.position.set(6,2.6,7).multiplyScalar(Math.max(1,1.35/camera.aspect));renderer.setSize(el.clientWidth,el.clientHeight)});resize.observe(el);
 renderer.setAnimationLoop(()=>{if(visible&&!document.hidden){controls.update();renderer.render(scene,camera)}});setReady(true);
 cleanup=()=>{observer.disconnect();resize.disconnect();renderer.setAnimationLoop(null);controls.dispose();draco.dispose();environment.dispose();scene.traverse((o:any)=>{o.geometry?.dispose();if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()});renderer.dispose();renderer.domElement.remove();api.current=null};
 }catch(e){console.error('3D studio unavailable',e);if(!disposed)setError(true)}})();return()=>{disposed=true;cleanup()};},[]);
 return <div className="studio"><div className="studio-top"><div><p className="eyebrow">THE INTERACTIVE ATELIER</p><h2>Every angle.<br/>Pure emotion.</h2></div><p>FERRARI 458 SPIDER<br/><span>A study in Italian performance</span></p></div><div ref={host} className="canvas-host" tabIndex={0} role="img" aria-label="Interactive 3D Ferrari 458 Spider. Drag to rotate, use zoom buttons, or use left and right arrow keys." onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();api.current?.key(e.key==='ArrowLeft'?.15:-.15)}}}/>{!ready&&!error&&<p className="model-status">Preparing your 3D experience…</p>}{error&&<div className="model-status"><p>The 3D studio is unavailable on this device.</p><a href="/cars/ferrari-296">Explore the Ferrari collection ↗</a></div>}<div className="studio-controls"><div className="paint-options" aria-label="Exterior paint">{[['#b9bec4','Argento silver'],['#8c0b12','Rosso red'],['#e4bb32','Giallo yellow'],['#202327','Nero graphite']].map(([c,n])=><button key={c} aria-label={n} aria-pressed={paint===c} style={{background:c}} onClick={()=>{setPaint(c);api.current?.paint(c)}}/>)}</div><span className="drag-hint">DRAG TO EXPLORE · MAKE IT YOURS</span><div className="control-buttons"><button aria-label="Zoom in" onClick={()=>api.current?.zoom(.85)}>+</button><button aria-label="Zoom out" onClick={()=>api.current?.zoom(1.15)}>−</button><button aria-label={rotate?'Pause rotation':'Resume rotation'} onClick={()=>{setRotate(!rotate);api.current?.rotate(!rotate)}}>{rotate?<Pause size={17}/>:<Play size={17}/>}</button><button aria-label="Reset camera" onClick={()=>api.current?.reset()}><RotateCcw size={17}/></button></div></div><p className="model-credit">3D model: Ferrari 458 by vicent091036 via Three.js. Paint visualisation is illustrative.</p></div>
}

